<?php

namespace ImTaxu\LaravelLicense\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

// IDE helpers for functions provided by Laravel
if (!function_exists('app')) {
    function app() {
        return new class {
            public function basePath($path = '') { return __DIR__ . '/../../../../' . $path; }
            public function environment(...$args) { return in_array('local', $args); }
        };
    }
}

// IDE helper for Laravel Facades
namespace Illuminate\Support\Facades {
    if (!class_exists('File')) {
        class File {
            public static function exists($path) { return file_exists($path); }
            public static function get($path) { return file_get_contents($path); }
            public static function put($path, $contents) { return file_put_contents($path, $contents); }
        }
    }
}

// IDE helper for Illuminate\Support\Str
namespace Illuminate\Support {
    if (!class_exists('Str')) {
        class Str {
            public static function random($length = 16) { return substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil($length/strlen($x)))), 1, $length); }
        }
    }
}

// IDE helper for Illuminate\Console\Command
namespace Illuminate\Console {
    if (!class_exists('Command')) {
        class Command {
            public function error($message) {}
            public function info($message) {}
            public function line($message) {}
        }
    }
}

if (!function_exists('config_path')) {
    function config_path($path = '') {
        return app()->basePath('config') . ($path ? '/' . $path : '');
    }
}

if (!function_exists('storage_path')) {
    function storage_path($path = '') {
        return app()->basePath('storage') . ($path ? '/' . $path : '');
    }
}

if (!function_exists('env')) {
    function env($key, $default = null) {
        return $default;
    }
}

// IDE helpers for Laravel classes
if (!class_exists('Illuminate\Console\Command')) {
    class_alias('ImTaxu\LaravelLicense\Helpers\CommandHelper', 'Illuminate\Console\Command');
}

if (!class_exists('Illuminate\Support\Facades\File')) {
    class_alias('ImTaxu\LaravelLicense\Helpers\FileHelper', 'Illuminate\Support\Facades\File');
}

if (!class_exists('Illuminate\Support\Facades\Storage')) {
    class_alias('ImTaxu\LaravelLicense\Helpers\StorageHelper', 'Illuminate\Support\Facades\Storage');
}

if (!class_exists('Illuminate\Support\Str')) {
    class_alias('ImTaxu\LaravelLicense\Helpers\StrHelper', 'Illuminate\Support\Str');
}

// Use statements moved to the top

class ObfuscateConfigCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'license:obfuscate';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Obfuscates the license configuration file and adds protection';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $configPath = config_path('license.php');
        
        if (!\Illuminate\Support\Facades\File::exists($configPath)) {
            $this->error('License configuration file not found. You must publish the file first:');
            $this->line('php artisan vendor:publish --tag=license-config');
            return 1;
        }

        // Read the original config content
        $originalContent = \Illuminate\Support\Facades\File::get($configPath);
        
        // Evaluate the config content and get it as an array
        $configArray = require $configPath;
        
        // Convert config array to JSON
        $configJson = json_encode($configArray);
        
        // Create a unique key (app name + domain + timestamp)
        $encryptionKey = md5(
            ($configArray['variables']['app_name'] ?? env('APP_NAME', 'Laravel')) . 
            ($configArray['variables']['domain'] ?? env('APP_URL', 'localhost')) . 
            'license-salt-' . env('APP_KEY', \Illuminate\Support\Str::random(32))
        );
        
        // Obfuscate the config JSON
        $encryptedConfig = $this->obfuscateConfig($configJson, $encryptionKey);
        
        // Create a checksum for the obfuscated config
        $checksum = md5($encryptedConfig . $encryptionKey);
        
        // Create a new PHP file containing the obfuscated config and checksum
        $obfuscatedContent = <<<PHP
<?php
// This file is automatically generated and should not be modified.
// To make changes, first edit the original config file,
// then run the 'php artisan license:obfuscate' command.

return [
    '_encrypted' => true,
    '_data' => '{$encryptedConfig}',
    '_checksum' => '{$checksum}',
    '_key' => '{$encryptionKey}',
];
PHP;

        // Backup the original config file
        $backupPath = storage_path('app/license-config-backup-' . date('Y-m-d-His') . '.php');
        \Illuminate\Support\Facades\File::put($backupPath, $originalContent);
        
        // Write the obfuscated content to the config file
        \Illuminate\Support\Facades\File::put($configPath, $obfuscatedContent);
        
        // Also save a copy of the obfuscated config to the vendor folder
        $vendorConfigPath = __DIR__ . '/../../config/license.php.obfuscated';
        \Illuminate\Support\Facades\File::put($vendorConfigPath, $obfuscatedContent);
        
        $this->info('License configuration file successfully obfuscated and protected!');
        $this->line('Backup of the original configuration file is stored at: ' . $backupPath);
        
        return 0;
    }

    /**
     * Obfuscate config content
     *
     * @param string $content
     * @param string $key
     * @return string
     */
    protected function obfuscateConfig(string $content, string $key): string
    {
        // Apply a simple XOR encryption
        $result = '';
        $keyLength = strlen($key);
        
        for ($i = 0; $i < strlen($content); $i++) {
            $result .= $content[$i] ^ $key[$i % $keyLength];
        }
        
        // Encode with Base64
        return base64_encode($result);
    }
}
